// <auto-generated />
using System;
using HastaneRandevu_Y225012153.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneRandevu_Y225012153.Migrations
{
    [DbContext(typeof(HastaneDbContext))]
    partial class HastaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.AnabilimDali", b =>
                {
                    b.Property<int>("AnabilimDaliID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnabilimDaliID"), 1L, 1);

                    b.Property<string>("AnabilimDaliAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnabilimDaliID");

                    b.ToTable("AnabilimDallari");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.CalismaSaati", b =>
                {
                    b.Property<int>("CalismaSaatiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalismaSaatiID"), 1L, 1);

                    b.Property<DateTime?>("CalismaGunu")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoktorID")
                        .HasColumnType("int");

                    b.HasKey("CalismaSaatiID");

                    b.HasIndex("DoktorID");

                    b.ToTable("CalismaSaatleri");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.Doktor", b =>
                {
                    b.Property<int>("DoktorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoktorID"), 1L, 1);

                    b.Property<int>("AnabilimDaliID")
                        .HasColumnType("int");

                    b.Property<string>("DoktorAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoktorID");

                    b.HasIndex("AnabilimDaliID");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"), 1L, 1);

                    b.Property<int>("DoktorID")
                        .HasColumnType("int");

                    b.Property<string>("HastaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaSoyadi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RandevuTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuID");

                    b.HasIndex("DoktorID");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.CalismaSaati", b =>
                {
                    b.HasOne("HastaneRandevu_Y225012153.Models.Domain.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.Doktor", b =>
                {
                    b.HasOne("HastaneRandevu_Y225012153.Models.Domain.AnabilimDali", "AnabilimDali")
                        .WithMany("Doktorlar")
                        .HasForeignKey("AnabilimDaliID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnabilimDali");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.Randevu", b =>
                {
                    b.HasOne("HastaneRandevu_Y225012153.Models.Domain.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("HastaneRandevu_Y225012153.Models.Domain.AnabilimDali", b =>
                {
                    b.Navigation("Doktorlar");
                });
#pragma warning restore 612, 618
        }
    }
}
